add_executable(event_dispatcher_test)
target_link_libraries(event_dispatcher_test
        PRIVATE
        star
)
target_sources(event_dispatcher_test
        PRIVATE
        src/test/event_dispatcher_test.cpp
)

add_executable(glm_test)
target_link_libraries(glm_test
        PRIVATE
        star
)
target_sources(glm_test
        PRIVATE
        src/test/glm_test.cpp
)